general:
  name: "track1"
  bpm: 100
  centerTemperature: 0.5

interpolates:
  interpolate_model: "cat-mel_2bar_big"
  interpolate_limit: 20
  interpolate_primary_secondary: true
  interpolate_arp_primary: true
  interpolate_arp_secondary: true
  interpolate_bass_primary: true
  interpolate_bass_secondary: true
  interpolate_pad_primary: true
  interpolate_pad_secondary: true

primaryMelody:
  primary_run: true
  primary_midiPath: null
  primary_minimumAleatoryNotes: 4
  primary_minimunUniqueNotes: 3
  primary_midiAleatoryPath: "resources/mid/ManuelMontero"
  primary_startTime_extractSubsequence: null
  primary_endTime_extractSubsequence: null
  primary_numberOfMelodies: 10
  primary_steps: [32, 64, 128]
  primary_rnn_model: ["mono_rnn", "lookback_rnn", "attention_rnn"]

secondaryMelody:
  melody_run: true
  melody_numberOfMelodies: 20
  melody_steps: [32, 64]
  melody_vae_model: ["cat-mel_2bar_big", "hierdec-mel_16bar"]

drums:
  drums_run: true
  drums_numberOfMelodies: 10
  drums_steps: [32, 64, 128]
  drums_vae_model: ["groovae_4bar" , "nade-drums_2bar_full", "hierdec-trio_16bar"]

bass:
  bass_run: true
  bass_midiPath: null
  bass_minimumAleatoryNotes: 2
  bass_minimunUniqueNotes: 2
  bass_midiAleatoryPath: "resources/mid/bass"
  bass_startTime_extractSubsequence: null
  bass_endTime_extractSubsequence: null
  bass_numberOfMelodies: 10
  bass_steps: [32, 64, 128]
  bass_rnn_model: ["basic_rnn", "lookback_rnn", "attention_rnn"]

arp:
  arp_run: true
  arp_midiPath: null
  arp_minimumAleatoryNotes: 4
  arp_minimunUniqueNotes: 4
  arp_midiAleatoryPath: "resources/mid/arp"
  arp_startTime_extractSubsequence: null
  arp_endTime_extractSubsequence: null
  arp_numberOfMelodies: 10
  arp_steps: [32, 64, 128]
  arp_rnn_model: ["mono_rnn", "lookback_rnn", "attention_rnn"]

pad:
  pad_run: true
  pad_midiPath: null
  pad_minimumAleatoryNotes: 2
  pad_minimunUniqueNotes: 2
  pad_midiAleatoryPath: "resources/mid/pad"
  pad_startTime_extractSubsequence: null
  pad_endTime_extractSubsequence: null
  pad_numberOfMelodies: 10
  pad_steps: [ 32, 64, 128 ]
  pad_rnn_model: [ "basic_rnn", "lookback_rnn", "attention_rnn" ]