general:
  name: "track1"

primaryMelody:
  primary_midiPath: "auto"
  primary_startTime_extractSubsequence: None
  primary_endTime_extractSubsequence: None
  primary_numberOfMelodies: 10
  primary_steps: 128
  primary_rnn_model: ["basic_rnn", "mono_rnn", "lookback_rnn", "attention_rnn"]



