general:
  name: "track1"
  bpm: 128
  centerTemperature: 0.6

interpolates:
  interpolate_model: "cat-mel_2bar_big"
  interpolate_limit: 20
  interpolate_primary_secondary: false
  interpolate_arp_primary: false
  interpolate_arp_secondary: false
  interpolate_bass_primary: false
  interpolate_bass_secondary: false
  interpolate_pad_primary: false
  interpolate_pad_secondary: false

chords:
  chords_run: true
  chords_scales: true
  chords_by_key: true
  chords_fromNoteToChord_n: 10
  chords_secondary_fromNoteToChord: true

primaryMelody:
  primary_run: false
  primary_midiPath: null
  primary_minimumAleatoryNotes: 4
  primary_minimunUniqueNotes: 3
  primary_midiAleatoryPath: "resources/mid/ManuelMontero"
  primary_startTime_extractSubsequence: null
  primary_endTime_extractSubsequence: null
  primary_numberOfMelodies: 10
  primary_steps: [32, 64, 128]
  primary_rnn_model: ["mono_rnn", "lookback_rnn", "attention_rnn"]

VAE:
  melody_run: false
  melody_numberOfMelodies: 20
  melody_steps: [32, 64]
  melody_vae_model: ["cat-mel_2bar_big"] #["cat-mel_2bar_big", "hierdec-mel_16bar"]
  melody_own_vae_ckpt:
  #  - ["deadmau5", "cat-mel_2bar_small", "model/deadmau5/train/model.ckpt-394"]

drums:
  drums_run: false
  drums_numberOfMelodies: 10
  drums_steps: [32, 64, 128]
  drums_vae_model: ["groovae_4bar" , "nade-drums_2bar_full", "hierdec-trio_16bar"]

bass:
  bass_run: false
  bass_midiPath: null
  bass_minimumAleatoryNotes: 2
  bass_minimunUniqueNotes: 2
  bass_midiAleatoryPath: "resources/mid/bass"
  bass_startTime_extractSubsequence: null
  bass_endTime_extractSubsequence: null
  bass_numberOfMelodies: 10
  bass_steps: [32, 64, 128]
  bass_rnn_model: ["basic_rnn", "lookback_rnn", "attention_rnn"]

arp:
  arp_run: false
  arp_midiPath: null
  arp_minimumAleatoryNotes: 4
  arp_minimunUniqueNotes: 4
  arp_midiAleatoryPath: "resources/mid/arp"
  arp_startTime_extractSubsequence: null
  arp_endTime_extractSubsequence: null
  arp_numberOfMelodies: 10
  arp_steps: [32, 64, 128]
  arp_rnn_model: ["mono_rnn", "lookback_rnn", "attention_rnn"]

pad:
  pad_run: false
  pad_midiPath: null
  pad_minimumAleatoryNotes: 2
  pad_minimunUniqueNotes: 2
  pad_midiAleatoryPath: "resources/mid/pad"
  pad_startTime_extractSubsequence: null
  pad_endTime_extractSubsequence: null
  pad_numberOfMelodies: 10
  pad_steps: [ 32, 64, 128 ]
  pad_rnn_model: [ "basic_rnn", "lookback_rnn", "attention_rnn" ]